### ISSUE TITLE
Cannot set a brand new flair (have to already have one set, then i can change it)

### ISSUE THREAD

**Issue by Rose-David** [Haptic-Apps/Slide#3019] opened 2019-05-14 22:45 UTC
Slide version: 6.2
Android version: 9

**Comment by Targetednuke** [comment] 2019-05-14 22:47
If this is an API limitation, thats cool, but if its a bug, please fix it

**Comment by Tensounder54** [comment] 2019-07-02 20:55
I'm not sure what could be causing this. @timawesomeness Any ideas?

**Comment by teknolog1k** [comment] 2023-02-15 14:32
Closing as development is on indefinite hiatus. If development restarts, and the issue is still present, then I can reopen it.

**Closed by teknolog1k** 2023-02-15 14:32 UTC
Labels: Bug, Needs Reproduction, Android Pie
